version: 3

images:
  base_image:
    name: python:3.9.23-slim

dependencies:
  python: requirements.txt
  galaxy: requirements.yml
  ansible_core:
    package_pip: ansible-core==2.14.18
  ansible_runner:
    package_pip: ansible-runner==2.3.4
  python_interpreter:
    package_system: python3
    python_path: /usr/local/bin/python3

additional_build_steps:
  prepend_base:
    - RUN mkdir -p /root/.config/openstack
    - COPY _build/clouds.yml /root/.config/openstack/clouds.yml
  append_final:
    - ENV ANSIBLE_FORCE_COLOR=1
    - ENV ANSIBLE_HOST_KEY_CHECKING=False
    - ENV PATH="/usr/local/bin:${PATH}"

options:
  user: root
  package_manager_path: /usr/bin/apt-get
