---
- name: Associate existing Floating IP to Load Balancer
  hosts: localhost
  gather_facts: no

  vars:
    cloud_name: "{{ cloud_name | default('openstack') }}"
    lb_name: "{{ lb_output.name | default('awx-test-lb-l4-corretto') }}"
    vip_port_id: "{{ lb_output.vip_port_id | default(omit) }}"
    existing_fip: "{{ existing_fip | default('5.9.220.190') }}"
    description: "Floating IP associato automaticamente al Load Balancer {{ lb_name }}"

  tasks:

    - name: Debug workflow input
      ansible.builtin.debug:
        msg:
          - "ðŸ—ï¸ Cloud: {{ cloud_name }}"
          - "ðŸ—ï¸ Load Balancer: {{ lb_name }}"
          - "ðŸ—ï¸ VIP Port ID: {{ vip_port_id | default('da determinare') }}"
          - "ðŸ—ï¸ Floating IP: {{ existing_fip }}"

    - name: Retrieve Load Balancer VIP Port ID (if not provided)
      when: vip_port_id is not defined
      ansible.builtin.command: >
        python3 -c "import openstack, json;
        conn=openstack.connect(cloud='{{ cloud_name }}');
        lb=conn.load_balancer.find_load_balancer('{{ lb_name }}');
        import sys;
        sys.exit(1) if not lb else None;
        full=conn.load_balancer.get_load_balancer(lb);
        print(full.vip_port_id)"
      register: vip_id_cmd
      changed_when: false
      failed_when: vip_id_cmd.rc != 0

    - name: Set VIP Port ID if retrieved
      when: vip_port_id is not defined
      ansible.builtin.set_fact:
        vip_port_id: "{{ vip_id_cmd.stdout }}"

    - name: Debug final VIP Port ID
      ansible.builtin.debug:
        msg: "âœ… VIP Port ID finale: {{ vip_port_id }}"

    - name: Associate existing Floating IP via SDK script
      ansible.builtin.command: >
        /usr/local/bin/assign_fip_lb.py
      environment:
        CLOUD_NAME: "{{ cloud_name }}"
        EXISTING_FIP: "{{ existing_fip }}"
        PORT_ID: "{{ vip_port_id }}"
        DESCRIPTION: "{{ description }}"

    - name: Success message
      ansible.builtin.debug:
        msg: "âœ… Floating IP {{ existing_fip }} associato con successo al Load Balancer {{ lb_name }}"
